### PR TITLE
Require whole active_support to support ActiveSupport v7

### PR DESCRIPTION
**Pull request by unasuke**
On ActiveSupport v7, raises this exeption when require minimum file.

```
uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
```

* https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support
* https://github.com/rails/rails/pull/43852

And, ActiveSupport v4 is deprecated now. So remove if-else of version.

### CODE REVIEW

**Comment by r7kamura** [comment]
Nice change 👍

**Comment by unasuke** [comment]
But travis has gone...?

**Comment by r7kamura** [comment]
Dropping support of activesupport 4 looks reasonable, but shouldn't we add version restriction at gemspec?

https://github.com/r7kamura/chrono/blob/403327de8806025d730655a5f98ed6cca19cde36/chrono.gemspec#L19

**Comment by unasuke** [comment]
> Dropping support of activesupport 4 looks reasonable, but shouldn't we add version restriction at gemspec?

‼️ ‼️ 

Yes, I will commit to this. I think the appropriate minimum version restriction is 5.2, are you ok?

https://guides.rubyonrails.org/maintenance_policy.html

**Comment by r7kamura** [comment]
> But travis has gone...?

Wait a minute, I'll fix it soon:

- https://github.com/r7kamura/chrono/pull/10

**Comment by r7kamura** [comment]
> Yes, I will commit to this. I think the appropriate minimum version restriction is 5.2, are you ok?

Looks good. If someone want to support lower versions, ask them to submit a pull request.

**Comment by unasuke** [comment]
@r7kamura rebased!

**Comment by r7kamura** [comment]
Thank you @unasuke! I just released chrono 0.5.0 🎉 🎄 ❄️ 

- https://rubygems.org/gems/chrono/versions/0.5.0

**Pull request merged**
