### PR TITLE
Check too many fields

### PR DESCRIPTION
**Pull request by nurse**

### CODE REVIEW

**Comment by r7kamura** [comment]
It might be better to separate validation logic from `#fields` method and explicitly validate fields in `Chrono::Schedule#initialize`

**Comment by nurse** [comment]
Which do you like `%r<\A[ \t]*(?:(?<field>(?<step>(?:\*|(?:\d+(?:-\d+)?))(?:/\d+)?)(?:,\g<step>)*)[       \t]+){4}\g<field>[ \t]*\z>` or `%r<\A[ \t]*(?:(?<field>[^ \t\r\n]+)[ \t]+){4}\g<field>[ \t]*\z>`?

**Comment by nurse** [comment]
I found `field` should be \S+ for future extension.

**Comment by r7kamura** [comment]
:v:

**Pull request merged**
